# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'synctity.ui'
#
# Created: Sat Aug 31 13:54:35 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Synctity(object):
    def setupUi(self, Synctity):
        Synctity.setObjectName(_fromUtf8("Synctity"))
        Synctity.resize(700, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/synctity.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Synctity.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Synctity)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonAddProfile = QtGui.QPushButton(self.groupBox_2)
        self.buttonAddProfile.setObjectName(_fromUtf8("buttonAddProfile"))
        self.horizontalLayout.addWidget(self.buttonAddProfile)
        self.buttonRemoveProfile = QtGui.QPushButton(self.groupBox_2)
        self.buttonRemoveProfile.setObjectName(_fromUtf8("buttonRemoveProfile"))
        self.horizontalLayout.addWidget(self.buttonRemoveProfile)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.listProfiles = QtGui.QListView(self.groupBox_2)
        self.listProfiles.setObjectName(_fromUtf8("listProfiles"))
        self.gridLayout_2.addWidget(self.listProfiles, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupProfile = QtGui.QGroupBox(self.centralwidget)
        self.groupProfile.setObjectName(_fromUtf8("groupProfile"))
        self.gridLayout = QtGui.QGridLayout(self.groupProfile)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupProfile)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.textProfileName = QtGui.QLineEdit(self.groupProfile)
        self.textProfileName.setObjectName(_fromUtf8("textProfileName"))
        self.gridLayout.addWidget(self.textProfileName, 0, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupProfile)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.listCommands = QtGui.QListView(self.groupProfile)
        self.listCommands.setObjectName(_fromUtf8("listCommands"))
        self.gridLayout.addWidget(self.listCommands, 2, 0, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonAddCommand = QtGui.QPushButton(self.groupProfile)
        self.buttonAddCommand.setAutoFillBackground(False)
        self.buttonAddCommand.setObjectName(_fromUtf8("buttonAddCommand"))
        self.horizontalLayout_2.addWidget(self.buttonAddCommand)
        self.buttonRemoveCommand = QtGui.QPushButton(self.groupProfile)
        self.buttonRemoveCommand.setObjectName(_fromUtf8("buttonRemoveCommand"))
        self.horizontalLayout_2.addWidget(self.buttonRemoveCommand)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 3)
        self.label = QtGui.QLabel(self.groupProfile)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.textPreSync = QtGui.QLineEdit(self.groupProfile)
        self.textPreSync.setObjectName(_fromUtf8("textPreSync"))
        self.gridLayout.addWidget(self.textPreSync, 4, 1, 1, 1)
        self.buttonPreSync = QtGui.QPushButton(self.groupProfile)
        self.buttonPreSync.setObjectName(_fromUtf8("buttonPreSync"))
        self.gridLayout.addWidget(self.buttonPreSync, 4, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupProfile)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.textPostSync = QtGui.QLineEdit(self.groupProfile)
        self.textPostSync.setObjectName(_fromUtf8("textPostSync"))
        self.gridLayout.addWidget(self.textPostSync, 5, 1, 1, 1)
        self.buttonPostSync = QtGui.QPushButton(self.groupProfile)
        self.buttonPostSync.setObjectName(_fromUtf8("buttonPostSync"))
        self.gridLayout.addWidget(self.buttonPostSync, 5, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupProfile, 0, 1, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.buttonForward = QtGui.QPushButton(self.groupBox)
        self.buttonForward.setObjectName(_fromUtf8("buttonForward"))
        self.horizontalLayout_3.addWidget(self.buttonForward)
        self.buttonReverse = QtGui.QPushButton(self.groupBox)
        self.buttonReverse.setObjectName(_fromUtf8("buttonReverse"))
        self.horizontalLayout_3.addWidget(self.buttonReverse)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 3)
        self.gridLayout_3.setRowStretch(0, 3)
        Synctity.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Synctity)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Synctity.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(Synctity)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuSynctus = QtGui.QMenu(self.menuBar)
        self.menuSynctus.setObjectName(_fromUtf8("menuSynctus"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        Synctity.setMenuBar(self.menuBar)
        self.dockConsole = QtGui.QDockWidget(Synctity)
        self.dockConsole.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockConsole.setObjectName(_fromUtf8("dockConsole"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textConsole = QtGui.QTextEdit(self.dockWidgetContents)
        self.textConsole.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        self.textConsole.setFont(font)
        self.textConsole.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textConsole.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textConsole.setObjectName(_fromUtf8("textConsole"))
        self.verticalLayout.addWidget(self.textConsole)
        self.dockConsole.setWidget(self.dockWidgetContents)
        Synctity.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockConsole)
        self.actionLoad = QtGui.QAction(Synctity)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(Synctity)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(Synctity)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionRunAway = QtGui.QAction(Synctity)
        self.actionRunAway.setObjectName(_fromUtf8("actionRunAway"))
        self.menuSynctus.addAction(self.actionLoad)
        self.menuSynctus.addAction(self.actionSave)
        self.menuSynctus.addAction(self.actionSaveAs)
        self.menuSynctus.addSeparator()
        self.menuSynctus.addAction(self.actionRunAway)
        self.menuBar.addAction(self.menuSynctus.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Synctity)
        QtCore.QObject.connect(self.buttonAddProfile, QtCore.SIGNAL(_fromUtf8("clicked()")), Synctity.onAddProfile)
        QtCore.QObject.connect(self.buttonRemoveProfile, QtCore.SIGNAL(_fromUtf8("clicked()")), Synctity.onRemoveProfile)
        QtCore.QObject.connect(self.textProfileName, QtCore.SIGNAL(_fromUtf8("editingFinished()")), Synctity.onProfileName)
        QtCore.QObject.connect(self.buttonAddCommand, QtCore.SIGNAL(_fromUtf8("clicked()")), Synctity.onAddCommand)
        QtCore.QObject.connect(self.buttonRemoveCommand, QtCore.SIGNAL(_fromUtf8("clicked()")), Synctity.onRemoveCommand)
        QtCore.QObject.connect(self.listProfiles, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), Synctity.onSelectProfile)
        QtCore.QObject.connect(self.listCommands, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), Synctity.onEditCommand)
        QtCore.QObject.connect(self.buttonForward, QtCore.SIGNAL(_fromUtf8("clicked()")), Synctity.onForward)
        QtCore.QObject.connect(self.buttonReverse, QtCore.SIGNAL(_fromUtf8("clicked()")), Synctity.onReverse)
        QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL(_fromUtf8("triggered()")), Synctity.onLoad)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL(_fromUtf8("triggered()")), Synctity.onSave)
        QtCore.QObject.connect(self.actionSaveAs, QtCore.SIGNAL(_fromUtf8("triggered()")), Synctity.onSaveAs)
        QtCore.QObject.connect(self.actionRunAway, QtCore.SIGNAL(_fromUtf8("triggered()")), Synctity.onQuit)
        QtCore.QObject.connect(self.textPreSync, QtCore.SIGNAL(_fromUtf8("editingFinished()")), Synctity.onTextSync)
        QtCore.QObject.connect(self.textPostSync, QtCore.SIGNAL(_fromUtf8("editingFinished()")), Synctity.onTextSync)
        QtCore.QObject.connect(self.buttonPreSync, QtCore.SIGNAL(_fromUtf8("clicked()")), Synctity.onPreSync)
        QtCore.QObject.connect(self.buttonPostSync, QtCore.SIGNAL(_fromUtf8("clicked()")), Synctity.onPostSync)
        QtCore.QMetaObject.connectSlotsByName(Synctity)

    def retranslateUi(self, Synctity):
        Synctity.setWindowTitle(_translate("Synctity", "Synctity", None))
        self.groupBox_2.setTitle(_translate("Synctity", "Profiles", None))
        self.buttonAddProfile.setText(_translate("Synctity", "+", None))
        self.buttonRemoveProfile.setText(_translate("Synctity", "-", None))
        self.groupProfile.setTitle(_translate("Synctity", "Edit Profile", None))
        self.label_2.setText(_translate("Synctity", "Name", None))
        self.label_3.setText(_translate("Synctity", "Commands", None))
        self.buttonAddCommand.setText(_translate("Synctity", "+", None))
        self.buttonRemoveCommand.setText(_translate("Synctity", "-", None))
        self.label.setText(_translate("Synctity", "Pre-Sync", None))
        self.buttonPreSync.setText(_translate("Synctity", "...", None))
        self.label_4.setText(_translate("Synctity", "Post-Sync", None))
        self.buttonPostSync.setText(_translate("Synctity", "...", None))
        self.groupBox.setTitle(_translate("Synctity", "Run profile", None))
        self.buttonForward.setText(_translate("Synctity", "Forward", None))
        self.buttonReverse.setText(_translate("Synctity", "Reverse", None))
        self.menuSynctus.setTitle(_translate("Synctity", "Synctity", None))
        self.menuHelp.setTitle(_translate("Synctity", "Help", None))
        self.dockConsole.setWindowTitle(_translate("Synctity", "Console", None))
        self.actionLoad.setText(_translate("Synctity", "Load", None))
        self.actionLoad.setShortcut(_translate("Synctity", "Ctrl+L", None))
        self.actionSave.setText(_translate("Synctity", "Save", None))
        self.actionSave.setShortcut(_translate("Synctity", "Ctrl+S", None))
        self.actionSaveAs.setText(_translate("Synctity", "Save as...", None))
        self.actionSaveAs.setShortcut(_translate("Synctity", "Ctrl+Shift+S", None))
        self.actionRunAway.setText(_translate("Synctity", "Run Away", None))

import resources_rc
