# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'synctus.ui'
#
# Created: Fri Aug  6 13:14:12 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Synctus(object):
    def setupUi(self, Synctus):
        Synctus.setObjectName("Synctus")
        Synctus.resize(700, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/synctity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Synctus.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Synctus)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonAddProfile = QtGui.QPushButton(self.groupBox_2)
        self.buttonAddProfile.setObjectName("buttonAddProfile")
        self.horizontalLayout.addWidget(self.buttonAddProfile)
        self.buttonRemoveProfile = QtGui.QPushButton(self.groupBox_2)
        self.buttonRemoveProfile.setObjectName("buttonRemoveProfile")
        self.horizontalLayout.addWidget(self.buttonRemoveProfile)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.listProfiles = QtGui.QListView(self.groupBox_2)
        self.listProfiles.setObjectName("listProfiles")
        self.gridLayout_2.addWidget(self.listProfiles, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupProfile = QtGui.QGroupBox(self.centralwidget)
        self.groupProfile.setObjectName("groupProfile")
        self.gridLayout = QtGui.QGridLayout(self.groupProfile)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.groupProfile)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.textProfileName = QtGui.QLineEdit(self.groupProfile)
        self.textProfileName.setObjectName("textProfileName")
        self.gridLayout.addWidget(self.textProfileName, 0, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupProfile)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.listCommands = QtGui.QListView(self.groupProfile)
        self.listCommands.setObjectName("listCommands")
        self.gridLayout.addWidget(self.listCommands, 2, 0, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonAddCommand = QtGui.QPushButton(self.groupProfile)
        self.buttonAddCommand.setAutoFillBackground(False)
        self.buttonAddCommand.setObjectName("buttonAddCommand")
        self.horizontalLayout_2.addWidget(self.buttonAddCommand)
        self.buttonRemoveCommand = QtGui.QPushButton(self.groupProfile)
        self.buttonRemoveCommand.setObjectName("buttonRemoveCommand")
        self.horizontalLayout_2.addWidget(self.buttonRemoveCommand)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 3)
        self.label = QtGui.QLabel(self.groupProfile)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.textPreSync = QtGui.QLineEdit(self.groupProfile)
        self.textPreSync.setObjectName("textPreSync")
        self.gridLayout.addWidget(self.textPreSync, 4, 1, 1, 1)
        self.buttonPreSync = QtGui.QPushButton(self.groupProfile)
        self.buttonPreSync.setObjectName("buttonPreSync")
        self.gridLayout.addWidget(self.buttonPreSync, 4, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupProfile)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.textPostSync = QtGui.QLineEdit(self.groupProfile)
        self.textPostSync.setObjectName("textPostSync")
        self.gridLayout.addWidget(self.textPostSync, 5, 1, 1, 1)
        self.buttonPostSync = QtGui.QPushButton(self.groupProfile)
        self.buttonPostSync.setObjectName("buttonPostSync")
        self.gridLayout.addWidget(self.buttonPostSync, 5, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupProfile, 0, 1, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonForward = QtGui.QPushButton(self.groupBox)
        self.buttonForward.setObjectName("buttonForward")
        self.horizontalLayout_3.addWidget(self.buttonForward)
        self.buttonReverse = QtGui.QPushButton(self.groupBox)
        self.buttonReverse.setObjectName("buttonReverse")
        self.horizontalLayout_3.addWidget(self.buttonReverse)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 3)
        self.gridLayout_3.setRowStretch(0, 3)
        Synctus.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Synctus)
        self.statusbar.setObjectName("statusbar")
        Synctus.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(Synctus)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuSynctus = QtGui.QMenu(self.menuBar)
        self.menuSynctus.setObjectName("menuSynctus")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        Synctus.setMenuBar(self.menuBar)
        self.dockConsole = QtGui.QDockWidget(Synctus)
        self.dockConsole.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockConsole.setObjectName("dockConsole")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textConsole = QtGui.QTextEdit(self.dockWidgetContents)
        self.textConsole.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.textConsole.setFont(font)
        self.textConsole.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textConsole.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textConsole.setObjectName("textConsole")
        self.verticalLayout.addWidget(self.textConsole)
        self.dockConsole.setWidget(self.dockWidgetContents)
        Synctus.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockConsole)
        self.actionLoad = QtGui.QAction(Synctus)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(Synctus)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(Synctus)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionRunAway = QtGui.QAction(Synctus)
        self.actionRunAway.setObjectName("actionRunAway")
        self.menuSynctus.addAction(self.actionLoad)
        self.menuSynctus.addAction(self.actionSave)
        self.menuSynctus.addAction(self.actionSaveAs)
        self.menuSynctus.addSeparator()
        self.menuSynctus.addAction(self.actionRunAway)
        self.menuBar.addAction(self.menuSynctus.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Synctus)
        QtCore.QObject.connect(self.buttonAddProfile, QtCore.SIGNAL("clicked()"), Synctus.onAddProfile)
        QtCore.QObject.connect(self.buttonRemoveProfile, QtCore.SIGNAL("clicked()"), Synctus.onRemoveProfile)
        QtCore.QObject.connect(self.textProfileName, QtCore.SIGNAL("editingFinished()"), Synctus.onProfileName)
        QtCore.QObject.connect(self.buttonAddCommand, QtCore.SIGNAL("clicked()"), Synctus.onAddCommand)
        QtCore.QObject.connect(self.buttonRemoveCommand, QtCore.SIGNAL("clicked()"), Synctus.onRemoveCommand)
        QtCore.QObject.connect(self.listProfiles, QtCore.SIGNAL("clicked(QModelIndex)"), Synctus.onSelectProfile)
        QtCore.QObject.connect(self.listCommands, QtCore.SIGNAL("doubleClicked(QModelIndex)"), Synctus.onEditCommand)
        QtCore.QObject.connect(self.buttonForward, QtCore.SIGNAL("clicked()"), Synctus.onForward)
        QtCore.QObject.connect(self.buttonReverse, QtCore.SIGNAL("clicked()"), Synctus.onReverse)
        QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL("triggered()"), Synctus.onLoad)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL("triggered()"), Synctus.onSave)
        QtCore.QObject.connect(self.actionSaveAs, QtCore.SIGNAL("triggered()"), Synctus.onSaveAs)
        QtCore.QObject.connect(self.actionRunAway, QtCore.SIGNAL("triggered()"), Synctus.onQuit)
        QtCore.QObject.connect(self.textPreSync, QtCore.SIGNAL("editingFinished()"), Synctus.onTextSync)
        QtCore.QObject.connect(self.textPostSync, QtCore.SIGNAL("editingFinished()"), Synctus.onTextSync)
        QtCore.QObject.connect(self.buttonPreSync, QtCore.SIGNAL("clicked()"), Synctus.onPreSync)
        QtCore.QObject.connect(self.buttonPostSync, QtCore.SIGNAL("clicked()"), Synctus.onPostSync)
        QtCore.QMetaObject.connectSlotsByName(Synctus)

    def retranslateUi(self, Synctus):
        Synctus.setWindowTitle(QtGui.QApplication.translate("Synctus", "Synctity", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Synctus", "Profiles", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAddProfile.setText(QtGui.QApplication.translate("Synctus", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRemoveProfile.setText(QtGui.QApplication.translate("Synctus", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.groupProfile.setTitle(QtGui.QApplication.translate("Synctus", "Edit Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Synctus", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Synctus", "Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAddCommand.setText(QtGui.QApplication.translate("Synctus", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRemoveCommand.setText(QtGui.QApplication.translate("Synctus", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Synctus", "Pre-Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPreSync.setText(QtGui.QApplication.translate("Synctus", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Synctus", "Post-Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPostSync.setText(QtGui.QApplication.translate("Synctus", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Synctus", "Run profile", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonForward.setText(QtGui.QApplication.translate("Synctus", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonReverse.setText(QtGui.QApplication.translate("Synctus", "Reverse", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSynctus.setTitle(QtGui.QApplication.translate("Synctus", "Synctity", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Synctus", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.dockConsole.setWindowTitle(QtGui.QApplication.translate("Synctus", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("Synctus", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setShortcut(QtGui.QApplication.translate("Synctus", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Synctus", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("Synctus", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("Synctus", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setShortcut(QtGui.QApplication.translate("Synctus", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRunAway.setText(QtGui.QApplication.translate("Synctus", "Run Away", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
