#!/bin/bash

# Script for packaging Synctity.
#
# Usage: $ package [tar | dmg]
#
# The dmg option (default) creates a dmg for Mac OS X.
# The tar option creates a tar of the source code to distribute for Linix-like systems.

type=${1:-"dmg"}
basedir="$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )"
echo "Base directory: $basedir"

if [ $type == "tar" ]; then
	echo "Packaging tar for Linux..."
	
	archive=$basedir/install/synctity.tar
	cd $basedir/..
	"$(pwd)"
	tar chvf $archive synctity/*.py synctity/doc/html synctity/startsynctity synctity/LICENSE
else
	echo "Packaging dmg for Mac OS X..."

	bundle=$basedir/dist/Synctity.app
	diskimg=$basedir/install/synctity.dmg

	# update the installer disk image
	hdiutil attach $diskimg
	rm -r /Volumes/Synctity/Synctity.app
	cp -R $bundle /Volumes/Synctity
	hdiutil unmount /Volumes/Synctity
fi

echo "Done."
exit

